language: php

php:
  - 7

#sudo: false
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - lftp

os: linux

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction

script:
  - php build.php -e=prod

after_success:
  - bash deploy.sh
