sudo: false
language: php
php:
  - 7.1
# download Cecil
install:
  - curl -SOL https://cecil.app/cecil.phar
# check version
before_script:
  - php cecil.phar -v
# build
script:
  - php cecil.phar build --quiet
# deploy
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  overwrite: true
  on:
    branch: source
# purge cache
after_deploy:
  - bash scripts/cache.sh
