sudo: false
language: php
php:
  - 7.1
# download PHPoole
install:
  #- curl -SOL https://github.com/PHPoole/PHPoole/releases/download/3.2.0/phpoole.phar
  - curl -SOL https://phpoole.org/phpoole.phar
# check version
before_script:
  - php phpoole.phar -v
# build
script:
  - php phpoole.phar build --quiet
# deploy
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  overwrite: true
  on:
    branch: source
# purge cache
after_deploy:
  - bash scripts/cache.sh
