language: php
php:
  - 7
sudo: false
# download PHPoole
install:
  - curl -SOL https://phpoole.org/phpoole.phar
# check version
before_script:
  - php phpoole.phar -v
# build
script:
  - php phpoole.phar build
# deploy
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  overwrite: true
  on:
    branch: source
# purge cache
after_deploy:
  - bash scripts/cache.sh
