title: "Cecil"
baseline: "Your content driven static site generator."
description: "Cecil is a CLI application that merges plain text files (written in Markdown), images and Twig templates to generate a static website."
baseurl: "https://cecil.app/"
author:
  name: "Arnaud Ligny"
  url: "https://arnaudligny.fr"
keywords: ["static", "generator", "SSG", "PHP", "Twig"]
social:
  twitter:
    site: Cecil_Static
    creator: ArnaudLigny
  github:
    repo: https://github.com/Cecilapp/Cecil
image: /images/cecil-card.png
menus:
  main:
    - id: documentation
      name: Docs
      url: documentation
      weight: 10
      enabled: true
    - id: download
      name: Download
      url: download
      weight: 30
      enabled: true
    - id : github
      name: GitHub
      url: https://github.com/Cecilapp/Cecil
      weight: 40
      enabled: false
    - id: index
      enabled: false
    - id: about
      enabled: false
    - id: cms
      enabled: false
    - id: hosting
      enabled: false
output:
  formats:
    - name: phar
      mediatype: 'application/octet-stream'
      extension: 'phar'
    - name: sha1
      mediatype: 'text/plain'
      extension: 'phar.sha1'
    - name: algolia
      mediatype: 'application/json'
      suffix: 'algolia'
      extension: 'json'
  pagetypeformats:
    homepage: ['html', 'algolia']
    section: ['html', 'atom']
theme:
  - netlify
release:
  name: cecil.phar
  sha1: cecil.phar.sha1
googleanalytics: UA-387892-21
gsv: LIvUncCjs-xtddzUhv7CNTHWsjXpOk0C4BL4KMRYUVM
docs_repo: https://github.com/Cecilapp/Cecil/edit/master/docs/
algolia:
  enabled: true
  application_id: 'PVTO81KCEC'
  search_api_key: 'd4f7a88b01ac073e9bb24dc264ead2dc'
  index: 'documentation'
static:
  exclude:
    #- '*.phar*' # dev only
    - 'cecil-demo.png'
    - '*.mp4'
    - 'tailwind.css'
