site:
  name: "Cecil"
  baseline: "Your content driven static site generator."
  description: "Cecil is a CLI application that merges plain text files (written in Markdown), images and Twig templates to generate a static website."
  baseurl: "https://cecil.app/"
  language: "en"
  author:
    name: "Arnaud Ligny"
    home: "https://arnaudligny.fr"
  keywords: ["static", "generator", "SSG", "PHP", "Twig"]
  output:
    formats:
      netlify_redirects:
        mediatype: 'text/plain'
        extension: ''
  virtualpages:
    _redirects:
      output: netlify_redirects
  menu:
    main:
      index:
        id: index
        enabled: false
      documentation:
        id: documentation
        name: Docs
        url: documentation
        weight: 10
      about:
        id: about
        name: About
        url: about
        weight: 20
        enabled: false
      download:
        id: download
        name: Download
        url: download
        weight: 30
      github:
        id: github
        name: GitHub
        url: https://github.com/Cecilapp/Cecil
        weight: 40
        enabled: false
  release:
    name: cecil.phar
    sha1: cecil.phar.sha1
  googleanalytics: 387892-21
  gsv: LIvUncCjs-xtddzUhv7CNTHWsjXpOk0C4BL4KMRYUVM
